{
  config,
  lib,
  pkgs,
  ...
}:
let
  cfg = config.lwm;

  startScript = pkgs.writeScript "start-lwm" ''
    #! ${pkgs.zsh}/bin/zsh
    # run daemon-reload so that sops-nix generated templates in ~/.config/environment.d
    # are read (they are generated by sops too late for the standard systemd env generator)
    systemctl --user daemon-reload
    systemctl --user unset-environment DISPLAY WAYLAND_DISPLAY
    ${pkgs.zsh}/bin/zsh --login -c "${pkgs.systemd}/bin/systemctl --user import-environment PATH XDG_DATA_DIRS"
    exec systemctl --user --wait start lwm.service
  '';

  inherit (lib)
    mkEnableOption
    mkIf
    mkOption
    types
    ;
in
{
  options.lwm = {
    enable = mkEnableOption "lwm";

    python = mkOption {
      type = types.package;
      default = pkgs.python3;
    };

    startScript = mkOption {
      type = types.package;
      default = startScript;
    };
  };

  config = mkIf cfg.enable {
    systemd.user.services.lwm =
      let
        pyEnv = cfg.python.withPackages (ps: [
          ps.qtile

          # Extra widgets
          ps.qtile-extras

          # Packages required by widgets
          ps.aiohttp # Weather
          ps.dbus-fast # Bluetooth
          ps.iwlib # Wifi
          ps.psutil # CPU
          ps.pulsectl-asyncio # PulseVolume

          # Packages required by config
          ps.pyyaml
          ps.pydantic
        ]);
      in
      {
        Unit = {
          Description = "lwm - Looniversity window manager";
        };

        Service = {
          Type = "simple";
          ExecStart = "${pyEnv}/bin/qtile start --backend wayland --config %h/.config/lwm";
          Restart = "on-failure";
          RestartSec = 1;
          TimeoutStopSec = 10;

          EnvironmentFile = mkIf (cfg.environmentFile != null) cfg.environmentFile;
        };
      };
  };
}
