version = 1
SPDX-PackageName = "Looniversity Site Configuration"
SPDX-PackageDownloadLocation = "https://github.com/sffjunkie/lwm"
SPDX-PackageSupplier = "Person: Simon Kennedy"

[[annotations]]
path = "**"
precedence = "closest"
SPDX-FileCopyrightText = "2026 Simon Kennedy (https://github.com/sffjunkie/lwm/)"
SPDX-License-Identifier = "MIT"
